FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY config/requirements.txt config/
RUN pip install --no-cache-dir -r config/requirements.txt

COPY source source
RUN mkdir -p files
